function s = rotcov(s,rot)
d = size(s,1);
if d==2 && isscalar(rot) % rot is a angle (2d)
    rot = [cos(rot) -sin(rot); sin(rot) cos(rot)];
elseif d==3 && numel(rot)==3 % rot is zyz angle in 3d
    rot = reshape([-sin(rot(1)).*sin(rot(3))+cos(rot(1)).*cos(rot(2)).*cos(rot(3)),...
        cos(rot(1)).*sin(rot(3))+cos(rot(2)).*cos(rot(3)).*sin(rot(1)),...
        -cos(rot(3)).*sin(rot(2)),...
        -cos(rot(3)).*sin(rot(1))-cos(rot(1)).*cos(rot(2)).*sin(rot(3)),...
        cos(rot(1)).*cos(rot(3))-cos(rot(2)).*sin(rot(1)).*sin(rot(3)),...
        sin(rot(2)).*sin(rot(3)),...
        cos(rot(1)).*sin(rot(2)),...
        sin(rot(1)).*sin(rot(2)),...
        cos(rot(2))],[3,3]); % by symolic toolbox
elseif d==3 && isscalar(rot)
    error('define 3d rotation required matrix or zyz angle')
end

s = rot * s * rot';
end